org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.252
neo_version_range=[21.1.0,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod properties
mod_id=dungeons2
mod_name=Dungeons II: The Sift
mod_license=MIT
mod_version=0.1.0
mod_group_id=io.github.ott2006.dungeons2
mod_authors=ott2006
mod_description=Brings the Sift dimension and other content from Minecraft Dungeons II into Minecraft: Singer's Meadow, Lullaby Hills, The Carapace, ichor, Blubs, Singers, Echo Golems, Sifters, Sculkers, the Monarch and much more.
