package io.github.ott2006.dungeons2.client.geo;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.ott2006.dungeons2.Dungeons2;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Nullable;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * An entity model defined in {@code assets/dungeons2/geo/<name>.json}. The files are generated by
 * {@code tools/gen_entities.py} together with the matching textures, so geometry and UV layout always agree.
 */
public final class GeoDefinition {
    private static final Map<String, GeoDefinition> CACHE = new HashMap<>();

    public record Cube(float x, float y, float z, float w, float h, float d, int u, int v, float inflate, boolean mirror) {
    }

    public record Bone(String name, @Nullable String parent, float px, float py, float pz, float rx, float ry, float rz, List<Cube> cubes) {
    }

    private final String name;
    private final int textureWidth;
    private final int textureHeight;
    private final Map<String, Bone> bones;

    private GeoDefinition(String name, int textureWidth, int textureHeight, Map<String, Bone> bones) {
        this.name = name;
        this.textureWidth = textureWidth;
        this.textureHeight = textureHeight;
        this.bones = bones;
    }

    public static synchronized GeoDefinition get(String name) {
        return CACHE.computeIfAbsent(name, GeoDefinition::load);
    }

    private static GeoDefinition load(String name) {
        String path = "/assets/" + Dungeons2.MOD_ID + "/geo/" + name + ".json";
        try (InputStream in = GeoDefinition.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("Missing entity model " + path);
            }
            JsonObject json = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            Map<String, Bone> bones = new LinkedHashMap<>();
            for (JsonElement el : json.getAsJsonArray("bones")) {
                JsonObject b = el.getAsJsonObject();
                JsonArray pivot = b.getAsJsonArray("pivot");
                JsonArray rot = b.getAsJsonArray("rotation");
                List<Cube> cubes = new ArrayList<>();
                for (JsonElement ce : b.getAsJsonArray("cubes")) {
                    JsonObject c = ce.getAsJsonObject();
                    JsonArray o = c.getAsJsonArray("origin");
                    JsonArray s = c.getAsJsonArray("size");
                    JsonArray uv = c.getAsJsonArray("uv");
                    cubes.add(new Cube(o.get(0).getAsFloat(), o.get(1).getAsFloat(), o.get(2).getAsFloat(),
                            s.get(0).getAsFloat(), s.get(1).getAsFloat(), s.get(2).getAsFloat(),
                            uv.get(0).getAsInt(), uv.get(1).getAsInt(),
                            c.has("inflate") ? c.get("inflate").getAsFloat() : 0.0F,
                            c.has("mirror") && c.get("mirror").getAsBoolean()));
                }
                String parent = b.has("parent") && !b.get("parent").isJsonNull() ? b.get("parent").getAsString() : null;
                String boneName = b.get("name").getAsString();
                bones.put(boneName, new Bone(boneName, parent,
                        pivot.get(0).getAsFloat(), pivot.get(1).getAsFloat(), pivot.get(2).getAsFloat(),
                        rot.get(0).getAsFloat(), rot.get(1).getAsFloat(), rot.get(2).getAsFloat(), cubes));
            }
            return new GeoDefinition(name, json.get("texture_width").getAsInt(), json.get("texture_height").getAsInt(), bones);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to load entity model " + path, e);
        }
    }

    public LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        Map<String, PartDefinition> parts = new HashMap<>();
        for (Bone bone : this.bones.values()) {
            PartDefinition parent = bone.parent() == null ? mesh.getRoot() : parts.get(bone.parent());
            if (parent == null) {
                throw new IllegalStateException(this.name + ": parent " + bone.parent() + " of " + bone.name() + " must come first");
            }
            CubeListBuilder builder = CubeListBuilder.create();
            for (Cube c : bone.cubes()) {
                builder.texOffs(c.u(), c.v()).mirror(c.mirror())
                        .addBox(c.x(), c.y(), c.z(), c.w(), c.h(), c.d(), new CubeDeformation(c.inflate()));
            }
            PartPose pose = PartPose.offsetAndRotation(bone.px(), bone.py(), bone.pz(),
                    bone.rx() * Mth.DEG_TO_RAD, bone.ry() * Mth.DEG_TO_RAD, bone.rz() * Mth.DEG_TO_RAD);
            parts.put(bone.name(), parent.addOrReplaceChild(bone.name(), builder, pose));
        }
        return LayerDefinition.create(mesh, this.textureWidth, this.textureHeight);
    }

    /** Looks up every bone of the baked model by name. */
    public Map<String, ModelPart> resolve(ModelPart root) {
        Map<String, ModelPart> result = new HashMap<>();
        for (Bone bone : this.bones.values()) {
            ModelPart parent = bone.parent() == null ? root : result.get(bone.parent());
            result.put(bone.name(), parent.getChild(bone.name()));
        }
        return result;
    }
}
