"""Small helper library for procedurally generating Minecraft-style pixel art.

All textures of the mod are generated by the scripts in this folder so that they
can be tweaked and re-generated at any time:

    python3 tools/gen_all.py
"""
import json
import math
import os
import random

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "src", "main", "resources", "assets", "dungeons2")


def out_path(*parts):
    path = os.path.join(ASSETS, *parts)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path


def hex2rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def clamp8(v):
    return int(max(0, min(255, round(v))))


def shade(c, f):
    """Multiply brightness of an rgb tuple."""
    if isinstance(c, str):
        c = hex2rgb(c)
    return tuple(clamp8(x * f) for x in c[:3])


def mix(a, b, t):
    if isinstance(a, str):
        a = hex2rgb(a)
    if isinstance(b, str):
        b = hex2rgb(b)
    return tuple(clamp8(a[i] * (1 - t) + b[i] * t) for i in range(3))


def value_noise(w, h, cell, seed, octaves=1, persistence=0.5):
    """Tileable value noise in range [0,1]."""
    rnd = np.random.default_rng(seed)
    total = np.zeros((h, w))
    amp = 1.0
    norm = 0.0
    c = cell
    for _ in range(octaves):
        gw = max(1, int(math.ceil(w / c)))
        gh = max(1, int(math.ceil(h / c)))
        grid = rnd.random((gh, gw))
        ys = np.arange(h) / c
        xs = np.arange(w) / c
        y0 = np.floor(ys).astype(int)
        x0 = np.floor(xs).astype(int)
        fy = ys - y0
        fx = xs - x0
        fy = fy * fy * (3 - 2 * fy)
        fx = fx * fx * (3 - 2 * fx)
        y1 = (y0 + 1) % gh
        x1 = (x0 + 1) % gw
        y0 %= gh
        x0 %= gw
        a = grid[np.ix_(y0, x0)]
        b = grid[np.ix_(y0, x1)]
        cc = grid[np.ix_(y1, x0)]
        d = grid[np.ix_(y1, x1)]
        top = a * (1 - fx)[None, :] + b * fx[None, :]
        bot = cc * (1 - fx)[None, :] + d * fx[None, :]
        layer = top * (1 - fy)[:, None] + bot * fy[:, None]
        total += layer * amp
        norm += amp
        amp *= persistence
        c = max(1, c / 2)
    return total / norm


def palette_map(values, palette):
    """Map an array of [0,1] values onto a list of colors (dark -> light)."""
    pal = [hex2rgb(p) if isinstance(p, str) else p for p in palette]
    n = len(pal)
    idx = np.clip((values * n).astype(int), 0, n - 1)
    h, w = values.shape
    img = Image.new("RGBA", (w, h))
    px = img.load()
    for y in range(h):
        for x in range(w):
            r, g, b = pal[idx[y, x]]
            px[x, y] = (r, g, b, 255)
    return img


def new(w, h, color=(0, 0, 0, 0)):
    return Image.new("RGBA", (w, h), color)


def put(img, x, y, c, a=255):
    if isinstance(c, str):
        c = hex2rgb(c)
    if 0 <= x < img.width and 0 <= y < img.height:
        img.putpixel((x, y), (c[0], c[1], c[2], a))


def get(img, x, y):
    return img.getpixel((x % img.width, y % img.height))


def save(img, *parts):
    path = out_path(*parts)
    img.save(path)
    return path


def save_mcmeta(data, *parts):
    path = out_path(*parts)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def jitter(img, amount, seed, mask_alpha=True):
    """Randomly brighten/darken pixels a little to add texture."""
    rnd = random.Random(seed)
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            if mask_alpha and a == 0:
                continue
            f = 1 + rnd.uniform(-amount, amount)
            px[x, y] = (clamp8(r * f), clamp8(g * f), clamp8(b * f), a)
    return img


def from_ascii(rows, palette):
    """Build an image from ASCII art. '.' or ' ' is transparent."""
    h = len(rows)
    w = max(len(r) for r in rows)
    img = new(w, h)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in ". ":
                continue
            col = palette[ch]
            if isinstance(col, str):
                col = hex2rgb(col)
            a = col[3] if len(col) > 3 else 255
            img.putpixel((x, y), (col[0], col[1], col[2], a))
    return img
